### ISSUE TITLE
Expose events for chunks?

### ISSUE THREAD

**Issue by MonkRocker** [flowjs/flow.js#213]
Hello.  

Not sure if I am encountering an actual bug or if I am just missing something.  As a file is completed, my backend is returning the file Id which was written to the DB on file completion.  For each chunk uploaded, it is returning a generic message "Continuing upload of <file>".

Problem is - in my flow-file-success handler, I don't seem to consistently getting the file Id as the last response received from the db.  Roughly half the time (and thus far no way to reliably duplicate) I get the "Continuing upload..." message.

`
function uploadCompete($file, message, chunk) {
            console.log("uploadComplete:", $file, message, chunk);
            vm.fileId = message;
            vm.showProgress = false;
            vm.progress = -1;
            vm.uploading = false;
            vm.clearFiles();
}
`

is my success handler.  Is there a way to get a success/response for each chunk?  it seems like my last few chunks might be completing out of order or something (is that even possible?)

**Comment by aayusharyan** [comment]
Hi @MonkRocker 
Please check the events `complete` , `fileError`, `fileProgress` and `fileSuccess`. 
Also, yes there is a possibility that chunks will be uploaded out of order.
It was an old issue and can be resolved with the suggestion above. I'll close the issue for now. Feel free to re-open if your problem is not solved. 🙇
