### ISSUE TITLE
Improving reliability of uploads on poor internet connections

### ISSUE THREAD

**Issue by quinncomendant** [flowjs/flow.js#259]
I'm using Flow.js for uploading mp3 files from a live lecture series. The event is in a remote location, where the internet is very bad: 0.1 - 1 Mb/s upload speed, 25% packet loss. Uploads frequently fail with a `fileError` event (with an empty message). However, uploading to other services such as Dropbox is 100% reliable.

Does anyone have suggestions for improving the reliability of Flow.js on poor internet connections? Is there a timeout setting or other options to force Flow.js to "never give up, keep trying"?

**Comment by AidasK** [comment]
Sure, you can adjust retry count, timeout and even a chunk size. Every option is documented

**Comment by quinncomendant** [comment]
Oh, awesome. 

So, it's clear that changing these may improve reliability:

        maxChunkRetries: 100,
        chunkRetryInterval: 3000,

But I'm not so sure about the other options. What else do you recommend? Would it be safer to have a smaller or larger chunk size? I'd appreciate your suggestions before I start with trial-and-error. 😁

**Comment by AidasK** [comment]
A higher chunk size means that more data is going to be lost if internet connection is unreliable. Though is chunk size is too small, upload speed and server load will increase. 1 chunk = 1 request to a server. 

Timeout, should be high enough to upload a chunk on minimal allowed speed. But not to high, so that it won't get stuck. 

There are no optimal settings, it is up to you to find a configuration which works best for your case.

**Comment by quinncomendant** [comment]
@AidasK, you mention "timeout", but I can't find a setting with that name. Do you mean `chunkRetryInterval`?

**Comment by AidasK** [comment]
Sorry, there is no such option, I think it is unnecessary
