### ISSUE TITLE
Uploading empty file IE10/IE11 hangs indefinitely

### ISSUE THREAD

**Issue by dolymood** [flowjs/flow.js#55]
This is a bug in IE10/IE11, see [uploading-empty-file-ie10-ie11-hangs-indefinitely](https://connect.microsoft.com/IE/feedback/details/813443/uploading-empty-file-ie10-ie11-hangs-indefinitely), but i think flow.js should handle it.

**Comment by waninlezu** [comment]
could you pls rollback this change?

Defect: when upload a empty file, **event flow::fileAdded fired in chrome but not in IE10+**,
in your case, you could handle empty file manually,not just ignore empty file in IE10+.

**Comment by AidasK** [comment]
So how should we solve it? I think ignore is better than crashed browser because of an empty file upload.

**Comment by waninlezu** [comment]
<code> 
  if (this.fire('fileAdded', f, event)) {
         if ((!ie10plus || ie10plus && file.size > 0)) {
               files.push(f);
          }
  }
</code>
to be consistent, fileAdded event need to be fire in chrome and IE, 
simplely we can stop put it in to files object to avoid uploading an empty file,
avoid uploading empty file with XHR request in IE10+  Is better.

**Comment by Duskfall** [comment]
This causes an error in folder upload firefox.

Steps to reproduce.
1) Have a folder with some non empty files
2) browse folder and select
3) The flow-files-added callback is called normally.

Problematic case

1) Have a folder with some empty and non empty files ( empty file is considered 0 bytes)
2) Do above steps 1 and 2 again.
3) Debugger goes to // https://github.com/flowjs/flow.js/issues/55 line in addFiles method
4) No files are added, because  flow-files-added is not triggered at all
