### ISSUE TITLE
First large file upload crashes Chrome

### ISSUE THREAD

**Issue by mattbodman** [flowjs/flow.js#58]
Strange behaviour.  If the first upload in a Chrome tab is "large" (perhaps requiring more than one chunk), the tab will crash.  However, if you first upload a smaller file, then the same large file, it works fine.  Interestingly, when I perform the same steps in Safari, it doesn't crash.  However, it does seem to temporarily hang my progress bar, leading me to think that Chrome just has a shorter timeout before crashing.  What is particular about the first upload that might cause this slowdown/crash?

**Comment by camillo777** [comment]
Hi! Does "flow" allows upload of files more than 4 GB?

**Comment by riordanmr** [comment]
It appears to me that flow loads the entire file into memory, chunk by chunk during the upload.  A browser that is a 32-bit application will crash after about 2GB of a file have been uploaded.  (Most browsers these days are 32-bit applications, even if they are running on 64-bit OSes.)  64-bit browsers will handle larger files, but not truly huge ones.

It seems to me that there must be a way to implement flow to not cache all of the data chunks in memory.  Does anyone have any thoughts on this?

**Comment by mattbodman** [comment]
I'm not sure that's the case.  I have flow uploading files over 100 GB

On Wed, Dec 16, 2015 at 1:49 PM, Mark Riordan <notifications@github.com>
wrote:

> It appears to me that flow loads the entire file into memory, chunk by
> chunk during the upload. A browser that is a 32-bit application will crash
> after about 2GB of a file have been uploaded. (Most browsers these days are
> 32-bit applications, even if they are running on 64-bit OSes.) 64-bit
> browsers will handle larger files, but not truly huge ones.
>
> It seems to me that there must be a way to implement flow to not cache all
> of the data chunks in memory. Does anyone have any thoughts on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flowjs/flow.js/issues/58#issuecomment-164981602>.
>



-- 

Matt Bodman

Australian Christian Channel

Ph +61 7 5478 1399
Mob +61 421 582 240
Direct +61 7 5313 8560
Skype mattbodman

**Comment by riordanmr** [comment]
@mattbodman:  Thanks for that comment.  I went back and ran the sample application (in the distribution as samples/Node.js) and did not see the browser memory leak there.  So it looks as if flow.js is exonerated, and the leak must be due to the way we are calling flow.js.

**Comment by evilaliv3** [comment]
@mattbodman i'm not completely sure.

i think what happened to @riordanmr  can happen.
in fact, from a fast look to the code i think that it is real that flow may end in having such a temporary allocation due to the garbage collector of the browser not acting that fast.


@AidasK may you clarify your thinking?

i see that that at line  https://github.com/flowjs/flow.js/blob/master/src/flow.js#L927 Flow.js currently pre-allocating a number of FlowChunk equal to this.size / this.flowObj.opts.chunkSize;  this prealllocation would not be the main issue but is  is there really the need for such a preallocation?

By the way the main issue can lie in the 'file.slice function returning a blob of the size of the chunk fro each call to it and it's up to the garbage collector to release it and the javascript garbage collector is known to be lazy and  different among the various browser implementations.

interesting: https://code.google.com/p/chromium/issues/detail?id=557205

@riordanmr are you still able to reproduce the bug?

**Comment by riordanmr** [comment]
@evilaliv3:  Our application definitely has a memory leak: it leaks almost exactly the amount of bytes equal to the number of bytes uploaded so far.  **However,** I suspect it's a problem with our application.  We calculate a cryptographic hash of the data during the upload and I suspect that we are inadvertently holding on to a reference to the data. 
I have since also tried the ng-flow sample ( https://github.com/flowjs/ng-flow/tree/master/samples/basic ) and like the flow.js demo app, it does not seem to have any significant leak.  (It accumulates FlowChunk objects, but these are small compared to the data being uploaded.)

**Comment by evilaliv3** [comment]
cool @mattbodman!

what are you using for calculating the hash?

do you know that flowjs implement a readHook that makes possible passing you every chunk in order to apply hashing/encryption in streaming? https://github.com/flowjs/flow.js/pull/111

from [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) we are finalizing the patch for encrypting in streaming using OpenPGP.js

**Comment by riordanmr** [comment]
@evilaliv3 We are using the forge sha1.js implementation.  Interestingly, this implementation had a bug for several years, which was fixed a few months ago.
We were not aware of the read hook.  So we implemented hashing by reconstituting the slice of the file, using flowFile.file, flowChunk.startByte, and flowChunk.endByte.  The approach you mention does sound better.
BTW, we did fix the memory leak in our application today.  As suggested above, it was not the fault of flow.js.

**Comment by evilaliv3** [comment]
from https://github.com/flowjs/flow.js:  readFileFn Optional function wrapping reading operation from the original file. To the function it will be passed the FlowFile, the startByte and endByte, the fileType and the FlowChunk.

i've still to enrich the documentation with an example sorry :)
