### ISSUE TITLE
generateUniqueIdentifier() doesn't really do that

### ISSUE THREAD

**Issue by dshefchik** [flowjs/flow.js#76]
I ran into a bug where multiple separate uploads had the same unique ID. Because it uses file size in generating the IDs, generateUniqueIdentifier() will generate the same uniqueId for identical files, making a server extremely confused during chunked uploads. 

I propose using a timestamp (or random number)  + path instead of file size.

**Comment by AidasK** [comment]
This is not a bug, ID is generated to identify each file. If file name and size matches, then we do not add this file to the list, because it is already uploaded. ID is also used to resume file upload, so every time, for the same file, ID should be the same. But you can use your own ID generation function.

**Comment by ericeslinger** [comment]
It's worth noting that this also can cause collisions if you have multiple users uploading files with identical characteristics at the same time (which is conceivably possible, but unlikely). While a reversible uniqueId is important for later resumability, it is potentially a security weakness. In my own system, I just pass in a generateUniqueIdentifier() that generates userId-specific uniques, and validate those userIds on the server side. That way, at least, two different users can upload otherwise-identical files at the same time.

**Comment by akididou** [comment]
Personally I do that to have a real Uniq ID.
I concat current uniqIdentifier and add current timestamp.

`  
import Flow from '@flowjs/flow.js';

 Flow.prototype.generateUniqueIdentifier = function (file) {
      const custom = this.opts.generateUniqueIdentifier;
      if (typeof custom === 'function') {
        return custom(file);
      }
      // Some confusion in different versions of Firefox
      const relativePath = file.relativePath || file.webkitRelativePath || file.fileName || file.name;
      return file.size + '-' + relativePath.replace(/[^0-9a-zA-Z_-]/img, '') + '-' + Date.now();
    };`
